### ISSUE TITLE
Documentation generation is failing

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/MLJLinearModels.jl#116]
Looks like an RSA key issue.

https://github.com/JuliaAI/MLJLinearModels.jl/runs/5353496598?check_suite_focus=true

**Comment by tlienart** [comment]
Not sure what's going on to be honest...

**Comment by tlienart** [comment]
Should be fixed

**Comment by tlienart** [comment]
(PS: I brought master and dev to the same state but I haven't tagged anything, not sure if you wanted to tag a patch release or wait a bit)

**Comment by ablaom** [comment]
Thanks @tlienart for sorting, and so quickly. I can confirm the failing run now passes: https://github.com/JuliaAI/MLJLinearModels.jl/actions/runs/1907784399

**Comment by ablaom** [comment]
I don't see a need to tag a release.
