### ISSUE TITLE
TagBot not working

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/MLJLinearModels.jl#126]

**Comment by DilumAluthge** [comment]
The job that failed: https://github.com/JuliaAI/MLJLinearModels.jl/runs/7670061578?check_suite_focus=true#step:3:50

**Comment by ablaom** [comment]
New release tagged since 0.6.2

https://github.com/JuliaAI/MLJLinearModels.jl/runs/7670061578?check_suite_focus=true#step:3:50

**Comment by DilumAluthge** [comment]
If you go to https://github.com/JuliaAI/MLJLinearModels.jl/actions/workflows/TagBot.yml, you can trigger another run manually.

**Comment by ablaom** [comment]
@DilumAluthge Thanks for that lightning response.

I've retriggered . I get green at the top but red again under "annotations": 
https://github.com/JuliaAI/MLJLinearModels.jl/actions/runs/2799833552
The log says we lack permission to access. But I don't understand. There is a DOCUMENTER_SECRET that was working before.

**Comment by DilumAluthge** [comment]
Looking at https://github.com/JuliaAI/MLJLinearModels.jl/runs/7669790446?check_suite_focus=true, it looks like the docs have not been pushing.

Can you delete and recreate a new Documenter key? The easiest way to do so is to install the DocumenterTools package and then run `DocumenterTools.genkeys()`, which will format the private key in the correct Base64 format that Documenter expects.

**Comment by ablaom** [comment]
Thanks. I'll do that in a bit.

**Comment by ablaom** [comment]
That seems to have fixed it thanks!
