### ISSUE TITLE
Unexpected behaviour with LogisticClassifier

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/MLJLinearModels.jl#131]
https://discourse.julialang.org/t/unexpected-behavior-in-logisticclassifier-mljlinearmodels/90013

**Comment by ablaom** [comment]
@tlienart Be great if you can take a look at this.

**Comment by jbrea** [comment]
Could the following line be the problem?
https://github.com/JuliaAI/MLJLinearModels.jl/blob/55f22b0492152badf66cfac37410341e7fb9a0b6/src/mlj/classifiers.jl#L72

**Comment by tlienart** [comment]
Thanks a lot @jbrea of course it's that line and https://github.com/JuliaAI/MLJLinearModels.jl/blob/55f22b0492152badf66cfac37410341e7fb9a0b6/src/mlj/classifiers.jl#L29 for the LogisticClassifier, I didn't think of the interface... btw it's probably better there's no default parameter in the interface 🙄
