### ISSUE TITLE
Improve documentation around available solvers

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/MLJLinearModels.jl#78]
I found I had to dig a bit to get this. Perhaps each doc-string states explicitly the solvers that are allowed (including full path for MLJ users, eg, `MLJLinearModels.Newton()`)

Also there is a broken link on the Solvers section of the manual to table of models (which I don't think specifies the available solvers for each model as the docs intimate??).

**Comment by tlienart** [comment]
Yes this is fair enough, I need to spend a weekend on this package and close off a few of the long standing issues

**Comment by ablaom** [comment]
I think the recent doc-PRs address this.
