### ISSUE TITLE
Bug: LassoRegressor from MLJLinearModels returns null vector but the one from ScikitLearn does not

### ISSUE THREAD

**Issue by Sh4pe** [JuliaAI/MLJLinearModels.jl#81]
I stumbled upon a case where the `LassoRegressor` from `MLJLinearModels` apparantly fails to solve a problem that can be solved using the `ScikitLearn` version.

In order to reproduce the bug, use the code from my repo [MLJLinearModels_bug](https://github.com/Sh4pe/MLJLinearModels_bug), especially the test DataFrame [here](https://github.com/Sh4pe/MLJLinearModels_bug/blob/master/data.csv.gz).

In the following code, I solve the same problem twice, but the `MLJLinearModels` version returns the null vector.

```julia
using DataFrames
using MLJ
using CSV
using GZip

load_df() = GZip.open("data.csv.gz") |> CSV.read

function test_lasso(df, the_model)
    y, X = unpack(df, ==(:y), !=(:y))

    the_machine = machine(the_model, X, y)
    train, test = partition(eachindex(y), 0.7, shuffle=false)

    fit!(the_machine, rows=train)

    ŷ = MLJ.predict(the_machine, rows=test)

    unique(ŷ)
end

@load LassoRegressor pkg="MLJLinearModels" name=LassoRegressorMLJ
@load LassoRegressor pkg="ScikitLearn" name=LassoRegressorSKLearn

let
    df = load_df()

    if test_lasso(df, LassoRegressorMLJ()) == [0.0]
        println("LassoRegressor from MLJLinearModels returns the null vector...")
    end

    if test_lasso(df, LassoRegressorSKLearn()) != [0.0]
        println("whereas the LassoRegressor from ScikitLearn returns a vector != 0")
    end
end
```

Also note that the solver spits out this warning:
```
[ Info: Training Machine{LassoRegressor} @638.
┌ Warning: No appropriate stepsize found via backtracking; interrupting.
└ @ MLJLinearModels ~/.julia/packages/MLJLinearModels/EIj86/src/fit/proxgrad.jl:50
┌ Warning: Proximal GD did not converge in 1000 iterations.
└ @ MLJLinearModels ~/.julia/packages/MLJLinearModels/EIj86/src/fit/proxgrad.jl:64
```

I'd expect the `MLJLinearModels` version to return a vector != 0  as well. This appears to be a bug.

**Versions** (see [Manifest.toml](https://github.com/Sh4pe/MLJLinearModels_bug/blob/master/Manifest.toml))
MLJ: version = "0.14.0"
MLJLinearModels: version = "0.5.0"
ScikitLearn: version = "0.6.2"

**Comment by ablaom** [comment]
@tlienart Reviewing old issues and wondered if this one could be closed?

**Comment by tlienart** [comment]
I think with the great additions from @jbrea to the Lasso code around normalisation, this should be closed now yes
