### ISSUE TITLE
Docs broken

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/MLJLinearModels.jl#99]
Probably the deployment URL needs updating In make.jl as we have moved to JuliaAI

**Comment by diegozea** [comment]
In the meantime; *JuliaHub* hosted docs are working: https://juliahub.com/docs/MLJLinearModels/FBSRA/0.5.5/

**Comment by ablaom** [comment]
The url is already fine. Going to try new deployment keys

**Comment by diegozea** [comment]
Thanks! They work perfectly now :)
